# Generated by Django 4.2.30 on 2026-05-07 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
            ],
            options={
                'verbose_name': 'المبنى',
                'verbose_name_plural': '1. المباني',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الطابق')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hospital_units.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'الطابق',
                'verbose_name_plural': '2. الطوابق',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('rooms_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الغرف')),
                ('beds_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='سعة الأسرة')),
                ('bathrooms_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الحمامات')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_units.building', verbose_name='المبنى')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital_units.floor', verbose_name='الطابق')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.ProtectedError, to=settings.AUTH_USER_MODEL, verbose_name='تحت إدارة')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': '4. الأقسام والمرافق',
            },
        ),
    ]
