# Generated by Django 4.2 on 2026-05-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_remove_department_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='building',
        ),
    ]
