# Generated by Django 4.2.30 on 2026-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_remove_department_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف المبنى'),
        ),
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الطابق'),
        ),
    ]
