# Generated by Django 4.2.30 on 2026-05-07 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الدور')),
                ('level', models.IntegerField(choices=[(1, '1 - صلاحيات كاملة (مدير عام)'), (2, '2 - إدارة صيانة ومشتريات'), (3, '3 - رؤساء أقسام (طلب صيانة)'), (4, '4 - فنيين (تنفيذ مهام)'), (5, '5 - عرض وتقارير فقط')], verbose_name='رقم مستوى الصلاحية')),
            ],
            options={
                'verbose_name_plural': 'الأدوار الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التخصص')),
            ],
            options={
                'verbose_name_plural': 'تخصصات الفنيين',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوظيفي')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='الدور الوظيفي')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialty', verbose_name='التخصص (للفنيين فقط)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
