# Generated by Django 4.2.30 on 2026-05-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_remove_department_building'),
        ('accounts', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='managing_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='hospital_units.department', verbose_name='رئيس القسم'),
        ),
    ]
