# Generated by Django 4.2.30 on 2026-05-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_managing_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='وصف المسمئ الوضيفي'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='وصف التخصص'),
        ),
    ]
