# Generated by Django 6.0.5 on 2026-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobtitlepermission_role_type_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitlepermission',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, verbose_name='عرض لوحة التحكم والتحليلات'),
        ),
    ]
