# Generated by Django 6.0.5 on 2026-06-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobtitlepermission_can_view_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_manage_system_setup', 'Can manage system setup')]},
        ),
        migrations.AddField(
            model_name='jobtitlepermission',
            name='can_manage_system_setup',
            field=models.BooleanField(default=False, verbose_name='Superuser / مسؤول تهيئة النظام'),
        ),
    ]
