# Generated by Django 6.0.5 on 2026-06-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_manage_system_setup', 'Can manage system setup'), ('can_view_audit_log', 'Can view audit log')]},
        ),
        migrations.AddField(
            model_name='jobtitlepermission',
            name='can_view_audit_log',
            field=models.BooleanField(default=False, verbose_name='عرض سجل العمليات'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('assign', 'تكليف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة مرور'), ('status_change', 'تغيير حالة')], db_index=True, max_length=40, verbose_name='نوع العملية')),
                ('model_name', models.CharField(db_index=True, max_length=120, verbose_name='اسم النموذج')),
                ('object_id', models.CharField(blank=True, max_length=120, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='البيانات القديمة')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الجديدة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['-created_at'],
                'permissions': [('can_view_audit_log', 'Can view audit log')],
                'indexes': [models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'), models.Index(fields=['user'], name='accounts_au_user_id_2e9d8e_idx'), models.Index(fields=['action_type'], name='accounts_au_action__f4611c_idx'), models.Index(fields=['model_name'], name='accounts_au_model_n_5922b8_idx')],
            },
        ),
    ]
