# Generated by Django 6.0.5 on 2026-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('assign', 'تكليف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('password_change', 'تغيير كلمة مرور'), ('status_change', 'تغيير حالة'), ('backup_create', 'إنشاء نسخة احتياطية'), ('backup_download', 'تحميل نسخة احتياطية'), ('backup_delete', 'حذف نسخة احتياطية')], db_index=True, max_length=40, verbose_name='نوع العملية'),
        ),
    ]
