# Generated by Django 6.0.5 on 2026-06-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='طلبات الصيانة', max_length=150, verbose_name='اسم النظام')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الجهة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/logos/', verbose_name='شعار النظام')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='نص الفوتر')),
                ('maintenance_policy_notes', models.TextField(blank=True, verbose_name='ملاحظات سياسة الصيانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
