# Generated by Django 6.0.5 on 2026-06-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallevel',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_levels', to='accounts.jobtitle'),
        ),
    ]
