# Generated by Django 6.0.5 on 2026-06-16 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_approvallevel_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallevel',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='approval_levels', to='accounts.jobtitle'),
            preserve_default=False,
        ),
    ]
