# Generated by Django 6.0.5 on 2026-06-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_jobtitlepermission_can_manage_user_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='accounts_us_user_id_6edbcb_idx',
            old_name='accounts_us_user_id_52f852_idx',
        ),
    ]
