# Generated by Django 4.2.30 on 2026-05-08 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_managing_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_units', '0002_remove_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('description', models.TextField(verbose_name='وصف العطل بالتفصيل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('assigned', 'تم التعيين (بانتظار الفني)'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('priority', models.CharField(choices=[('low', 'منخفضة (روتينية)'), ('medium', 'متوسطة'), ('high', 'عالية (مستعجلة)'), ('critical', 'حرجة (طوارئ فورية)')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('assigned_technician', models.ForeignKey(blank=True, limit_choices_to={'role__level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts.profile', verbose_name='الفني المكلف')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hospital_units.department', verbose_name='القسم المعطل')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('required_specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specialty', verbose_name='التخصص المطلوب للصيانة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-created_at'],
            },
        ),
    ]
