# Generated by Django 4.2.30 on 2026-05-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='title',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('assigned', 'تم التعيين (بانتظار الفني)'), ('in_progress', 'قيد التنفيذ'), ('awaiting_parts', 'قيد التنفيذ (بانتظار قطع غيار)'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
