# Generated by Django 4.2.30 on 2026-05-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_managing_department'),
        ('maintenance', '0002_remove_maintenancerequest_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='اسم قطعة الغيار')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('is_available', models.BooleanField(default=False, verbose_name='هل القطعة متوفرة؟')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('available_in_stock', '  (بانتظار تعميد الصرف) متوفره '), ('not_available_in_stock', 'غير متوفره (بانتظار توفر القطعة)'), ('awaiting_parts', ' تم تعميد الصرف (بانتضتر المهندس)'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=50, verbose_name='حالة طلب القطعة')),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'role__level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='المهندس الذي طلب القطعة')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'قطعة غيار مطلوبة',
                'verbose_name_plural': 'قطع الغيار المطلوبة',
            },
        ),
    ]
