# Generated by Django 4.2.30 on 2026-05-17 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0003_requestsparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('critical', 'حرجة (طوارئ فورية)'), ('high', 'عالية (مستعجلة)'), ('medium', 'متوسطة'), ('low', 'منخفضة (روتينية)')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requester',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب'),
        ),
    ]
