# Generated by Django 4.2.30 on 2026-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancerequest_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsparepart',
            name='agreement_role_level_1',
            field=models.BooleanField(default=False, verbose_name='موافقة مدير مكتب الخدمات'),
        ),
        migrations.AddField(
            model_name='requestsparepart',
            name='agreement_role_level_2',
            field=models.BooleanField(default=False, verbose_name='موافقة مدير عام الخدمات'),
        ),
        migrations.AddField(
            model_name='requestsparepart',
            name='agreement_role_level_3',
            field=models.BooleanField(default=False, verbose_name='موافقة مدير اداره الصيانة'),
        ),
        migrations.AddField(
            model_name='requestsparepart',
            name='agreement_role_level_4',
            field=models.BooleanField(default=False, verbose_name='موافقة رئيس قسم الصيانة'),
        ),
        migrations.AlterField(
            model_name='requestsparepart',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='هل القطعة متوفرة؟'),
        ),
    ]
