# Generated by Django 4.2.30 on 2026-05-18 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_sparepartrequest_delete_requestsparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ تقديم الطلب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
    ]
