# Generated by Django 4.2.30 on 2026-05-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_sparepartrequest_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='agreement_role_level_1',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='agreement_role_level_2',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='agreement_role_level_3',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='agreement_role_level_4',
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='agreement',
            field=models.IntegerField(default=0, max_length=1, verbose_name='الموافقة '),
        ),
    ]
