# Generated by Django 4.2.30 on 2026-05-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_managing_department'),
        ('maintenance', '0008_remove_sparepartrequest_agreement_role_level_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='required_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialty', verbose_name='التخصص المطلوب للصيانة'),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='agreement',
            field=models.IntegerField(default=0, verbose_name='الموافقة '),
        ),
    ]
