# Generated by Django 4.2.30 on 2026-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_maintenancerequest_required_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('waiting_for_acceptance', ' في انتظار التعميد'), ('accepted', ' تم تعميد  (بانتضتر رد مدير المشتريات)'), ('not_available_in_stock', 'غير متوفره (بانتظار توفر القطعة)'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='waiting_for_acceptance', max_length=50, verbose_name='حالة طلب القطعة'),
        ),
    ]
