# Generated by Django 4.2.30 on 2026-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_sparepartrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='agreement',
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='acceptance',
            field=models.IntegerField(default=0, verbose_name=' مستوائ التعميد'),
        ),
    ]
