# Generated by Django 4.2.30 on 2026-05-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_description_specialty_description'),
        ('maintenance', '0011_remove_sparepartrequest_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='cause',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenaces_reject', to='accounts.profile', verbose_name=' الذي رفض طلب الصيانة'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='cause',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_reject', to='accounts.profile', verbose_name=' الذي رفض طلب القطعة'),
        ),
    ]
