# Generated by Django 4.2.30 on 2026-05-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenancerequest_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='complete_report',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='تقرير النجاح'),
        ),
    ]
