# Generated by Django 4.2.30 on 2026-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_maintenancerequest_complete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='acceptance',
            field=models.IntegerField(default=0, verbose_name=' مستوائ التعميد'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('assigned', 'تم التعيين (بانتظار الفني)'), ('in_progress', 'قيد التنفيذ'), ('awaiting_parts', 'قيد التنفيذ (بانتظار قطع غيار)'), ('awaiting_for_acceptance', 'بانتظار تعميد تقرير الانجاز'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
    ]
