# Generated by Django 4.2.30 on 2026-06-01 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_maintenancerequest_acceptance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='order_kind',
            field=models.CharField(choices=[('store_requisition', 'طلب صرف مخزني'), ('purchase_requisition', 'طلب صرف مخزني')], default=1, max_length=100, verbose_name='نوع الطلب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('waiting_for_acceptance', ' في انتظار التعميد'), ('accepted', ' تم تعميد   (بانتضتر رد مدير المشتريات)'), ('not_available_in_stock', 'غير متوفره (بانتظار توفر القطعة)'), ('completed_available_parts', '  قبول صرف القطع المتوفره'), ('completed', ' مكتمل'), ('parts_rejected', ' تم رفض بعض القطع  (يرجى تعديل الطلب)'), ('rejected', 'مرفوض/ملغى')], default='waiting_for_acceptance', max_length=50, verbose_name='حالة طلب القطعة'),
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='اسم قطعة الغيار')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('is_accepted_department_manger', models.IntegerField(choices=[(-1, 'مرفوض'), (0, 'قيد الانتظار'), (1, 'مقبول')], default=0, verbose_name='هل تم قبول الطلب من قبل رىيس القسم؟')),
                ('is_accepted_maintenance_manager', models.IntegerField(choices=[(-1, 'مرفوض'), (0, 'قيد الانتظار'), (1, 'مقبول')], default=0, verbose_name='هل تم قبول الطلب من قبل مدير الصيانة؟')),
                ('is_accepted_director', models.IntegerField(choices=[(-1, 'مرفوض'), (0, 'قيد الانتظار'), (1, 'مقبول')], default=0, verbose_name='هل تم قبول الطلب من قبل مدير عام؟')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='maintenance.sparepartrequest', verbose_name='طلب القطعة')),
            ],
        ),
    ]
