# Generated by Django 4.2.30 on 2026-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_maintenancerequest_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartrequest',
            name='order_kind',
            field=models.CharField(choices=[('store_requisition', 'طلب صرف مخزني'), ('purchase_requisition', 'طلب شراء')], max_length=100, verbose_name='نوع الطلب'),
        ),
    ]
