# Generated by Django 6.0.5 on 2026-06-03 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_sparepartrequest_order_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='acceptance',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='complete_report',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='spareparts',
            name='is_accepted_department_manger',
        ),
        migrations.RemoveField(
            model_name='spareparts',
            name='is_accepted_director',
        ),
        migrations.RemoveField(
            model_name='spareparts',
            name='is_accepted_maintenance_manager',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_rejected',
            field=models.BooleanField(default=1, verbose_name='رفض القطعه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='is_rejected',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='رفض جميع القطع القطعه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spareparts',
            name='acceptance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name=' مستوائ التعميد'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='is_rejected',
            field=models.BooleanField(default=1, verbose_name='رفض القطعه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('assigned', 'تم التعيين (بانتظار الفني)'), ('in_progress', 'قيد التنفيذ'), ('awaiting_parts', 'قيد التنفيذ (بانتظار قطع غيار)'), ('spare_parts_rejected', 'تم رفض قطع الغيار'), ('obtained_parts', 'قيد التنفيذ (تم الحصول على قطع غيار)'), ('awaiting_completed_report_acceptance', 'بانتظار تعميد تقرير الانجاز'), ('completed_report_rejected', 'بانتظار تعميد تقرير الانجاز'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='acceptance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name=' مستوائ التعميد'),
        ),
        migrations.CreateModel(
            name='complete_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_report', models.CharField(blank=True, max_length=1000, null=True, verbose_name='تقرير النجاح')),
                ('is_rejected', models.BooleanField(verbose_name='رفض تقرير الانجاز')),
                ('cause', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض')),
                ('acceptance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name=' مستوائ التعميد')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_report', to='maintenance.maintenancerequest', verbose_name='طلب الصيانه')),
            ],
        ),
    ]
