# Generated by Django 6.0.5 on 2026-06-03 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_remove_maintenancerequest_acceptance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartrequest',
            name='is_rejected',
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='is_rejected',
            field=models.BooleanField(blank=True, null=True, verbose_name='رفض القطعه'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='maintenance.sparepartrequest', verbose_name='طلب القطعة'),
        ),
    ]
