# Generated by Django 6.0.5 on 2026-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_remove_sparepartrequest_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='رفض القطعه'),
        ),
    ]
