# Generated by Django 6.0.5 on 2026-06-04 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_maintenancerequest_is_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_report',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='complete_report',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_complete_reports', to=settings.AUTH_USER_MODEL, verbose_name='رفض بواسطة'),
        ),
        migrations.AddField(
            model_name='complete_report',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='complete_report',
            name='status',
            field=models.CharField(choices=[('awaiting_acceptenace', ' في انتظار التعميد'), ('accepted', 'تم القبول'), ('rejected', 'تم الرفض')], default='awaiting_acceptenace', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='رفض بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفض'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_spare_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='رفض بواسطة'),
        ),
        migrations.AddField(
            model_name='sparepartrequest',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='Issued_confirmation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name=' مستوائ التعميد'),
        ),
        migrations.AlterField(
            model_name='complete_report',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='رفض تقرير الانجاز'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('assigned', 'تم التعيين (بانتظار الفني)'), ('accept_assignment_start_progress', 'بدا التنفيذ'), ('reject_assignment', 'رفض التكليف'), ('awaiting_parts', 'قيد التنفيذ (بانتظار قطع غيار)'), ('spare_parts_rejected', 'تم رفض قطع الغيار'), ('obtained_parts', 'قيد التنفيذ (تم الحصول على قطع غيار)'), ('awaiting_completed_report_acceptenace', 'بانتظار تعميد تقرير الانجاز'), ('completed_report_rejected', 'تم رفض تقرير الانجاز'), ('completed', 'مكتمل'), ('rejected', 'مرفوض/ملغى')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_for_accepenace', ' في انتظار التعميد'), ('waiting_purchase_accepted_parts', 'في انتضار شراء القطغ المقبوله'), ('bought_available_parts', 'تم شراء القطع المقبوله (في انتظار صرف القطع المقبوله)'), ('issue_available_parts_issued_waiting_confirmation', 'بانتظار صرف القطع المقبوله من المخزن'), ('avaliable_parts_issued_waiting_confirmation', 'تم صرف القطع المقبوله (في انتظار تأكيد استلام القطع)'), ('avaliable_parts_issued', 'تم صرف القطع المقبوله والتأكيد'), ('rejected', 'مرفوض/ملغى')], default='awaiting_for_accepenace', max_length=60, verbose_name='حالة طلب القطعة'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='رفض القطعه'),
        ),
        migrations.CreateModel(
            name='CompleteReportApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'تم القبول'), ('rejected', 'تم الرفض')], max_length=20, verbose_name='القرار')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القرار')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_report_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعمد')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='maintenance.complete_report', verbose_name='تقرير الإنجاز')),
            ],
            options={
                'verbose_name': 'تعميد تقرير إنجاز',
                'verbose_name_plural': 'تعميدات تقارير الإنجاز',
                'unique_together': {('report', 'approver')},
            },
        ),
        migrations.CreateModel(
            name='SparePartApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'تم القبول'), ('rejected', 'تم الرفض')], max_length=20, verbose_name='القرار')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القرار')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعمد')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='maintenance.sparepartrequest', verbose_name='طلب قطع الغيار')),
            ],
            options={
                'verbose_name': 'تعميد طلب قطع غيار',
                'verbose_name_plural': 'تعميدات طلبات قطع الغيار',
                'unique_together': {('request', 'approver')},
            },
        ),
    ]
