# Generated by Django 6.0.5 on 2026-06-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_complete_report_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_dashboard', 'Can view maintenance dashboard')], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
    ]
