# Generated by Django 6.0.5 on 2026-06-04 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_alter_maintenancerequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('notification_type', models.CharField(choices=[('maintenance_assigned', 'تم تعيين طلب صيانة'), ('maintenance_rejected', 'تم رفض طلب صيانة'), ('assignment_rejected', 'رفض تكليف مهندس'), ('spare_part_needs_approval', 'طلب قطع غيار يحتاج تعميد'), ('spare_part_rejected', 'تم رفض طلب قطع غيار'), ('spare_part_purchase_ready', 'قطع غيار بانتظار التوفير'), ('spare_part_ready_to_issue', 'قطع غيار جاهزة للصرف'), ('spare_part_waiting_confirmation', 'قطع غيار بانتظار التأكيد'), ('spare_part_issued', 'تم صرف قطع الغيار'), ('complete_report_needs_approval', 'تقرير إنجاز يحتاج تعميد'), ('complete_report_rejected', 'تم رفض تقرير إنجاز'), ('maintenance_completed', 'اكتمل طلب الصيانة'), ('general', 'عام')], default='general', max_length=60, verbose_name='نوع الإشعار')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإشعار')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('related_complete_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.complete_report', verbose_name='تقرير الإنجاز المرتبط')),
                ('related_maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة المرتبط')),
                ('related_spare_part_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.sparepartrequest', verbose_name='طلب قطع الغيار المرتبط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='maintenance_recipie_64b194_idx'), models.Index(fields=['recipient', 'is_read'], name='maintenance_recipie_f8a2e5_idx'), models.Index(fields=['created_at'], name='maintenance_created_183a05_idx')],
            },
        ),
    ]
