# Generated by Django 6.0.5 on 2026-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('maintenance_needs_acceptance', 'طلب صيانة جديد يحتاج معالجة'), ('maintenance_assigned', 'تم تعيين طلب صيانة'), ('maintenance_rejected', 'تم رفض طلب صيانة'), ('assignment_rejected', 'رفض تكليف مهندس'), ('spare_part_needs_approval', 'طلب قطع غيار يحتاج تعميد'), ('spare_part_rejected', 'تم رفض طلب قطع غيار'), ('spare_part_purchase_ready', 'قطع غيار بانتظار التوفير'), ('spare_part_ready_to_issue', 'قطع غيار جاهزة للصرف'), ('spare_part_waiting_confirmation', 'قطع غيار بانتظار التأكيد'), ('spare_part_issued', 'تم صرف قطع الغيار'), ('complete_report_needs_approval', 'تقرير إنجاز يحتاج تعميد'), ('complete_report_rejected', 'تم رفض تقرير إنجاز'), ('maintenance_completed', 'اكتمل طلب الصيانة'), ('general', 'عام')], default='general', max_length=60, verbose_name='نوع الإشعار'),
        ),
    ]
